-- SELECT el.NAME
-- FROM COFFEE_LIST cl, EMPLOYEE_LIST el
-- WHERE el.PREFERRED_COFFEE = cl.NAME and el.COWORKER_PAID = 0
-- ORDER BY cl.PRICE DESC
-- LIMIT 1;

-- SELECT SUM(cl.Price)
-- FROM Coffee_List cl, EMPLOYEE_LIST el
-- WHERE el.PREFERRED_COFFEE = cl.NAME;


-- UPDATE EMPLOYEE_LIST
-- SET COWORKER_PAID = 0;









